###################################################
#
# Makefile
# Author: Methodios Zacharioudakis
#
####################################################

all:	shell

shell:	shell.c
		gcc -o shell shell.c

clean:
	rm -f shell
	clear